#!/usr/bin/env bash
OLD_DIR=`pwd`
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
cd $SCRIPT_DIR
./sl -V --latex=./math/zfc.tex --html=./html_out math/zfc.sl
pdflatex -halt-on-error ./math/zfc.tex
